package cli

import (
	"fmt"
	"os"
	"path/filepath"

	json "github.com/goccy/go-json"
)

const (
	daemonSecretFileFlagName = "daemon-secret-file"
	daemonSecretFileFlag     = "--" + daemonSecretFileFlagName
)

type daemonSecretPayload struct {
	Token      string `json:"token,omitempty"`
	AuthPass   string `json:"auth_pass,omitempty"`
	AuthBearer string `json:"auth_bearer,omitempty"`
}

func writeDaemonSecretFile(payload daemonSecretPayload) (string, error) {
	dir := getDaemonDir()
	if err := os.MkdirAll(dir, 0700); err != nil {
		return "", fmt.Errorf("failed to create daemon directory: %w", err)
	}

	file, err := os.CreateTemp(dir, ".daemon-secret-")
	if err != nil {
		return "", fmt.Errorf("failed to create daemon secret file: %w", err)
	}
	path := file.Name()
	keep := false
	defer func() {
		_ = file.Close()
		if !keep {
			_ = os.Remove(path)
		}
	}()

	if err := file.Chmod(0600); err != nil {
		return "", fmt.Errorf("failed to secure daemon secret file: %w", err)
	}

	data, err := json.Marshal(payload)
	if err != nil {
		return "", fmt.Errorf("failed to marshal daemon secrets: %w", err)
	}

	if _, err := file.Write(data); err != nil {
		return "", fmt.Errorf("failed to write daemon secrets: %w", err)
	}
	if err := file.Close(); err != nil {
		return "", fmt.Errorf("failed to close daemon secret file: %w", err)
	}

	keep = true
	return path, nil
}

func readDaemonSecretFile(path string) (daemonSecretPayload, error) {
	var payload daemonSecretPayload
	if path == "" {
		return payload, nil
	}

	cleanPath := filepath.Clean(path)
	data, err := os.ReadFile(cleanPath) // #nosec G304 -- daemon secret path is generated by this client and carried by a hidden internal flag.
	if err != nil {
		return payload, fmt.Errorf("failed to read daemon secret file: %w", err)
	}

	if err := json.Unmarshal(data, &payload); err != nil {
		return payload, fmt.Errorf("failed to parse daemon secret file: %w", err)
	}

	return payload, nil
}

func applyDaemonSecretFile() error {
	if daemonSecretFile == "" {
		return nil
	}

	path := daemonSecretFile
	payload, err := readDaemonSecretFile(path)
	removeErr := os.Remove(path)
	if err != nil {
		return err
	}
	if removeErr != nil && !os.IsNotExist(removeErr) {
		return fmt.Errorf("failed to remove daemon secret file: %w", removeErr)
	}

	authToken = payload.Token
	authPass = payload.AuthPass
	authBearer = payload.AuthBearer
	daemonSecretFile = ""
	return nil
}
